# 线上配置文件
# @author <a href="https://github.com/Hardork">老山羊</a>
# 
server:
  port: 8081
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx:3306/bi
    username: xxx
    password: xxx
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: xxx
    port: 6379
    timeout: 5000
    password: 123456
  rabbitmq:
    host: xxx
    username: xxx
    password: xxx
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''