spring:
  application:
    name: hwqbi
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.240.155:3306/bi
    username: root
    password: 123456
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 1
    host: 47.98.240.155
    port: 6379
    timeout: 5000
  mail:
    host: smtp.qq.com
    username: 1602370456@qq.com
    password: fzzfwwfoembojhci
    emailFrom: 1602370456@qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true

  rabbitmq:
    host: 47.98.240.155
    username: admin
    password: 123
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8081
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx
# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: AKIDTtPuIWbRCuXxCE7oMejaJ3d192pZKtFu
    secretKey: Tq5EAya4MQjwCSbXGRUiokaEgz5AAzmd
    region: ap-shanghai
    bucket: hwq-1317946928

yuapi:
  client:
    access-key: ifvmmt5c82stlecbi9xet2ih0kdh4ez6
    secret-key: 6r527qvdzp25mm7g0rizvo1yzf30f68o