#spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#  # session 配置
#  session:
#    # todo 取消注释开启分布式 session（须先配置 Redis）
#    store-type: redis
#    # 30 天过期
#    timeout: 2592000
#  # 数据库配置
#  # todo 需替换配置
#  data:
#    mongodb:
#      uri: mongodb://localhost/chart
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://xxx.xxx.xxx.xxx:3306/bi
#    username: xxx
#    password: xxx
#  # Redis 配置
#  # todo 需替换配置，然后取消注释
#  redis:
#    database: 2
#    host: xxx.xxx.xxx.xxx
#    port: 6379
#    timeout: 5000
#  # 邮件
#  mail:
#    host: smtp.qq.com
#    username: xxx@qq.com
#    password: xxx
#    emailFrom: xxx@qq.com
#    properties:
#      mail:
#        smtp:
#          ssl:
#            enable: true
#  rabbitmq:
#    host: xxx.xxx.xxx.xxx
#    username: xxx
#    password: xxx
#    # 初始化消费者数量
#    initConsumer: 2
#    # 最大消费者数量
#    maxConsumer: 4
#  # 文件上传
#  servlet:
#    multipart:
#      # 大小限制
#      max-file-size: 10MB
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
#      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
#      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
## 对象存储
## todo 需替换配置
#cos:
#  client:
#    accessKey: xxx
#    secretKey: xxx
#    region: xxx
#    bucket: xxx
## yucongming
#yuapi:
#  client:
#    access-key: xxx
#    secret-key: xxx
## 讯飞星火
#spark:
#  hostUrl: https://spark-api.xf-yun.com/v2.1/chat
#  appid: xxx
#  apiSecret: xxx
#  apiKey: xxx
## 当前服务器地址（共享链接生成）
#backend:
#  protocol: http
#  ip: localhost
#  port: 8000
#  prefix: add_other_data
#xxl:
#  job:
#    admin:
#      addresses: http://xxx.xxx.xxx.xxx:8088/xxl-job-admin
#      login-username: xxx
#      login-pwd: xxx
#    accessToken: default_token
#    executor:
#      appname: dataLoom-executor
#      ip: 127.0.0.1
#      port: 9999
#      logpath: /data/applogs/xxl-job/jobhandler
#      logretentiondays: 30
## 优惠券生产者配置
#rocketmq:
#  name-server: xxx.xxx.xxx.xxx:9876
#  producer:
#    group: coupon_producer
#    send-message-timeout: 2000
#    retry-times-when-send-failed: 1
#    retry-times-when-send-async-failed: 1