package com.hwq.dataloom.core.ops.constants;

public interface TraceTaskConstants {
    String CONVERSATION_TRACE = "CONVERSATION_TRACE";
    String WORKFLOW_TRACE = "WORKFLOW_TRACE";
    String MESSAGE_TRACE = "MESSAGE_TRACE";
    String MODERATION_TRACE = "MODERATION_TRACE";
    String SUGGESTED_QUESTION_TRACE = "SUGGESTED_QUESTION_TRACE";
    String DATASET_RETRIEVAL_TRACE = "DATASET_RETRIEVAL_TRACE";
}